# Generated by Django 4.1.2 on 2022-10-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordinfo',
            options={'verbose_name': 'Password Info', 'verbose_name_plural': 'Password Info'},
        ),
        migrations.AlterModelTable(
            name='passwordinfo',
            table='password_info',
        ),
    ]
