# Generated by Django 4.1.2 on 2022-10-19 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passwords', '0002_alter_passwordinfo_options_alter_passwordinfo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
