# Generated by Django 4.1.2 on 2022-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_alter_passwordinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordinfo',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='passwordinfo',
            name='user_or_email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
